name: Deploy to Render on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install All Dependencies and Build (via root script)
        run: npm run build

      - name: 🚀 Trigger Render Deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
